webserver/config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resource :animation do
      member do
        get :current_frame, :defaults => { :format => :json }
        get :last_frames, :defaults => { :format => :json }
      end
    end

    resource :gallery, except: [:new, :edit, :index] do
      resources :videos, only: [:create, :show, :destroy]
    end
  end

  match '/email', to: 'email#create', via: 'post'

  get 'galleries/', to: 'galleries#index', as: 'galleries/index'
  root 'landing#index'

end

webserver/app/models/animation.rb
SVG_NODE = 	<<-SVG
<?xml version="1.0"?>
<svg
width="960" height="540"
version="1.1"
baseProfile="full"
xmlns="http://www.w3.org/2000/svg">
SVG

class Animation < ActiveRecord::Base
	belongs_to :room
	has_many :frames

	@@s3 = Aws::S3::Client.new(
		region: 'us-east-1',
		credentials: Aws::Credentials.new(Rails.configuration.s3_access_key_id, Rails.configuration.s3_secret_access_key)
	)

	def current_frame
		create_next_frame if frames.empty? || (frames.last.expired? && !complete?)
		frames.last
	end

	def complete?
		frames.size == number_of_frames and frames.last.expired?
	end

	def frames_remaining
		number_of_frames - frames.size
	end

	private

	def create_next_frame
		frame = frames.create
		frame.image_url = "frames/#{id}/#{frame.id}"

		if frame.save
			schedule_frame_completion frame.id
		end
	end

	def schedule_frame_completion frame_id
		Rufus::Scheduler.singleton.in "#{timer_per_frame}s" do
			canvas = Canvas.new room.id

			# Store the current canvas image into S3
			@@s3.put_object(
				bucket: Rails.configuration.s3_bucket,
				body: "#{SVG_NODE}#{canvas.get}</svg>",
				key: "frames/#{self.id}/#{frame_id.to_s}",
				content_type: "image/svg+xml"
			)

			canvas.clear

			if complete?
				# Create a new animation for the public room
				if room.id == 1
					room.create_animation(
				    number_of_frames: 75,
				    timer_per_frame: 60,
				    video_framerate: 15
				  )
				end
				# Render the video on AWS Lambda
				Lambduh.render self
			end
		end
	end
end

webserver/app/controllers/animations_controller.rb
class AnimationsController < ApplicationController
  DEFAULT_NUMBER_OF_FRAMES = 60
  DEFAULT_TIMER_PER_FRAME = 30
  DEFAULT_VIDEO_FRAME_RATE = 15
  TIMER_UNITS = [['seconds'], ['minutes']]

  @@s3 = Aws::S3::Resource.new(
    region: 'us-east-1',
    access_key_id: Rails.configuration.s3_access_key_id,
    secret_access_key: Rails.configuration.s3_secret_access_key
  )

  include Password

  password do
    id = params[:room_id]
    Room.find(id).password if id && id != 'public'
  end

  def new
    room = Room.find params[:room_id]
    @animation = room.build_animation
  end

  def create
    room = Room.find params[:room_id]
    @animation = room.build_animation animation_params
    if @animation.save
      redirect_with_password room
    else
      render :new
    end
  end

  def current_frame
    animation = Room.find(params[:room_id]).animation
    respond_to do |format|
      format.json {
        render :json => {
          expiration: animation.current_frame.expiration,
          number: animation.frames.size + 1,
          complete: animation.complete?
        }
      }
    end
  end

  def last_frames
    num = params[:num].to_i
    room = Room.find params[:room_id]
    animation = room.animation

    if num <= animation.frames.length - 1
      frames = animation.frames[animation.frames.length - 1 - num .. animation.frames.length - 2]

      frames = frames.map do |f|
        @@s3.bucket(Rails.configuration.s3_bucket)
          .object(f.image_url)
          .presigned_url(:get, expires_in: 1800)
      end

      respond_to do |format|
        format.json { render json: frames }
      end
    else
      respond_to do |format|
        format.json { render json: "Index out of bounds." }
      end
    end
  end

  private

  def animation_params
    p = params.require(:animation).permit(
      :number_of_frames,
      :timer_per_frame,
      :video_framerate
    )
    p[:timer_per_frame] = p[:timer_per_frame].to_i * 60 if params[:timer_units] == 'minutes'
    return p
  end
end

webserver/app/helpers/animations_helper.rb
module AnimationsHelper
end

webserver/app/views/animations/new.html.erb
<div class="page-header">
  <%= link_to 'Back', url_with_password(@animation.room), :class => 'btn btn-default' %>
  <h1>Create a New Animation</h1>
</div>

<%= form_for @animation, url: room_animation_path do |f| %>
  <%= form_password %>

  <div class="control-group">
    <%= f.label :number_of_frames %>
    <%= f.number_field :number_of_frames, value: AnimationsController::DEFAULT_NUMBER_OF_FRAMES %>
  </div>

  <div class="control-group">
    <%= f.label :timer_per_frame %>
    <%= f.number_field :timer_per_frame, value: AnimationsController::DEFAULT_TIMER_PER_FRAME %>
    <%= select_tag :timer_units, options_for_select(AnimationsController::TIMER_UNITS) %>
  </div>

  <div class="control-group">
    <%= f.label :video_framerate %>
    <%= f.number_field :video_framerate, value: AnimationsController::DEFAULT_VIDEO_FRAME_RATE %>
  </div>

  <%= f.submit 'Create Animation', :class=>"btn btn-default" %>
<% end %>

<br/>

<div class="row">
  <span>Total time to create animation:</span>
  <span id="total_time"></span>
  <span id="total_time_units"></span>
</div>

<div class="row">
  <span>Total rendered video length:</span>
  <span id="video_length"></span>
  <span id="video_length_units"></span>
</div>