webserver/config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resource :animation do
      member do
        get :current_frame, :defaults => { :format => :json }
        get :last_frames, :defaults => { :format => :json }
      end
    end

    resource :gallery, except: [:new, :edit, :index] do
      resources :videos, only: [:create, :show, :destroy]
    end
  end

  match '/email', to: 'email#create', via: 'post'

  get 'galleries/', to: 'galleries#index', as: 'galleries/index'
  root 'landing#index'

end

webserver/app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

webserver/app/helpers/landing_helper.rb
module LandingHelper
end

webserver/app/views/landing/index.html.erb
<div class="page-header">
  <h1>Frame-By-Frame <small><%= t :landing_title %></small></h1>
</div>

<div class="btn-group" role="group" aria-label="..." padding-bottom="18px">
  <%= link_to t(:public_room_button), room_path(:public), :method => :get, :class => "btn btn-lg btn-default" %>
  <%= link_to t(:new_room_button), new_room_path, :method => :get, :class => "btn btn-lg btn-default" %>
  <%= link_to t(:list_rooms_button), rooms_path, :method => :get, :class => "btn btn-lg btn-default" %>
  <%= link_to "List of Galleries", galleries_index_path, :method => :get, :class => "btn btn-lg btn-default" %>
</div>

<p style="margin-top: 20px;">
  Frame by Frame is a web application where many anonymous users can collaborate to create frame animations.
  All users draw on a single canvas which is routinely saved as a frame to be used in generating an animation.
  After a frame is saved it is ‘onioned’ onto a new canvas as transparent layer helping users draw cohesive
  animations. Users will also have access to a chat system shared between the community. In addition to the
  public area users can create private drawing and share them with their friends via shared URLs in emails.
</p>