webserver/config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resource :animation do
      member do
        get :current_frame, :defaults => { :format => :json }
        get :last_frames, :defaults => { :format => :json }
      end
    end

    resource :gallery, except: [:new, :edit, :index] do
      resources :videos, only: [:create, :show, :destroy]
    end
  end

  match '/email', to: 'email#create', via: 'post'

  get 'galleries/', to: 'galleries#index', as: 'galleries/index'
  root 'landing#index'

end

webserver/app/models/gallery.rb
class Gallery < ActiveRecord::Base
	belongs_to :room
	has_many :videos

	def is_public
		if self.room.password == nil
			is_public = true
		else
			is_public = false
		end
		return is_public
	end

	def self.public_galleries
		Room.where(password: nil).map do |room|
			room.gallery
		end
	end

	def name
		return room.name
	end

end

webserver/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

	include Password

	password do
		id = params[:room_id]
    Room.find(id).password if id && id != 'public'
	end

	def index
		@galleries = Gallery.all
		@public_galleries = []
		@galleries.each do |gallery|
			if gallery.is_public
				@public_galleries << gallery
			end
		end
	end

	def show
		@room = Room.find(params[:room_id])
		@gallery = @room.gallery
	end

	def update
		@gallery = Room.find(params[:room_id]).gallery
	end

	def destroy
		@gallery = Room.find(params[:room_id]).gallery
		@gallery.destroy
	end

	private

	def gallery_params
		p = params.require(:gallery).permit()

		if params[:room][:private] == '1'
			if !(@room && @room.password)
				p[:password] = SecureRandom.urlsafe_base64
			end
		else
			p[:password] = nil
		end

		return p
	end

	def render_access_forbidden
		render plain: 'Access forbidden', status: :forbidden
	end

	def is_global_room
		id = params[:id]
		id == 'public' || id == 1
	end

end

webserver/app/helpers/galleries_helper.rb
module GalleriesHelper
end

webserver/app/views/galleries/index.html.erb
<div class="page-header">
  <h1>Public Galleries</h1>
</div>

<div class="row-fluid">
  <%= link_to 'Home', root_path, :class => "btn btn-default"  %>
</div>


<table class="table">
  <tr>
    <th>Gallery Name</th>
  </tr>
  <% if @public_galleries %>
	  <% @public_galleries.each do |gallery| %>
	    <tr>
	      <td><%= link_to gallery.name, room_gallery_path(gallery.room, gallery) %></td>
	    </tr>
	  <% end %>
  <% end %>
</table>

webserver/app/views/galleries/show.html.erb
<div class="page-header">
  <h1><%= @room.name %></h1>
</div>

<div class="row-fluid">
  <%= link_to 'Home', root_path, :class => "btn btn-default"  %>
  <%= link_to 'Room', url_with_password(@room), :class => 'btn btn-default' %>
</div>

<% if @gallery.videos.first %>
<table class="table">
  <tr>
    <th>Video Name</th>
    <th>Upload Date</th>
  </tr>

  <% @gallery.videos.each do |video| %>
    <tr>
	    <td><%= link_to video.name, url_with_password([@room, :gallery, video]) %></td>
	    <td><%= video.created_at %></td>
	  </tr>
  <% end %>
</table>
<% else %>
  <strong>No videos have been created yet!</strong>
<% end %>